type User @table {
  email: String!
  createdAt: Timestamp!
  displayName: String
  photoUrl: String
  isAdmin: Boolean
}

type Survey @table {
  creator: User!
  title: String!
  status: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type Question @table {
  survey: Survey!
  text: String!
  type: String!
  order: Int!
  createdAt: Timestamp!
  options: [String]
}

type Response @table {
  respondent: User!
  survey: Survey!
  submittedAt: Timestamp!
}

type Answer @table {
  response: Response!
  question: Question!
  value: String!
}